;---------------------------------------------------------------------
; debug.inc.asm - log ring buffer + HUD, + bitmap text rendering
;
;== FUNCTIONS: =======================================================
;draw:
;	- debug_draw_glyph(x,y,col,char)		draw one 8x8 character
;	- debug_print(x,y,col,str_ptr)			draw a string (handles \n)
;	- debug_print_int(x,y,col,val)			draw a signed integer
;	- debug_print_label_int(x,y,col,lbl,n)	draw "label: 123"
;log:
;	- debug_log(str_ptr)					add a line to log ring
;	- debug_log_label_int(label, value)		log "label: 123"
;	- debug_render_log()					draw log lines on screen
;	- debug_toggle()						flip visibility on/off
;	- is_debug_hud_enabled()				returns 1 if HUD is on
;util:
;	- strlen_simple()						counts bytes (w/o null)
;=====================================================================
;
; font data lives in font_data.inc.ams, auto-generated by gen_font.py
; each glyph is 8 bytes: 8 rows of 8 bits, eg
; 0x30 = 00110000 =   ##    
; 0x78 = 01111000 =  ####   
; 0xcc = 11001100 = ##  ##  
; 0xcc = 11001100 = ##  ##  
; 0xfc = 11111100 = ######  
; 0xcc = 11001100 = ##  ##  
; 0xcc = 11001100 = ##  ##  
; 0x00 = 00000000 =         
;
; keeping debug stuff bundled with font for now, TODO: extract later
;---------------------------------------------------------------------

%ifndef DEBUG_INC
%define DEBUG_INC

%include "font_data.inc.asm"

%define DEBUG_GLYPH_W 8		; pixels per glyph column 
%define DEBUG_GLYPH_H 8		; pixels per glyph row

; log config
%define LOG_LINE_LENGTH 60	; max chars per log line (including NULL)
%define LOG_LINES		8	; lines kept in ring buffer

section .data
	; visibility flag - F3 to toggle
	debug_hud_enabled	db 1

section .bss
	alignb 8
	int_buf		resb 16		; scratch for int->ascii
	;ring buffer storage: LOG_LINES * LOG_LINE_LENGTH bytes:
	log_buffer	resb LOG_LINES * LOG_LINE_LENGTH
	log_head	resd 1		; next slot to write (0..LOG_LINES-1)
	log_count	resd 1		; how many slots populated (0..LOG_LINES)

section .text
;================================================================
; debug_draw_glyph: draw a single 8x8 char to the framebuffer
;----------------------------------------------------------------
; C equivalent:
;	void debug_draw_glyph(int x, int y, uint32_t colour, char ch,
;						  int font_first_char, int font_last_char) {
;		if (ch < font_first_char || ch > font_last_char) return;
;		if (x < 0 || x > WINDOW_W-8 || y < 0||y > WINDOW_H-8) return;
;		uint8_t *glyph = font_8x8 + (ch - font_first_char) * 8;
;		uint32_t *row_ptr = &framebuffer[y * WINDOW_W + x];
;		for (int r = 0; r < 8; r++) {
;			uint8_t bits = glyph[r];
;			for (int c = 0; c < 8; c++)
;				if (bits & (0x80 >> c))
;					row_ptr[c] = colour;
;			row_ptr += WINDOW_W;
;		}
;	}
;----------------------------------------------------------------
; in: edi = x, esi = y, edx = ARGB colour, ecx = character
;================================================================
debug_draw_glyph:
	push rbx
	push r12
	push r13
	push r14
	push r15

	; early ret if char outside our font range
	cmp ecx, font_first_char ; in font_data.inc.asm
	jl .out
	cmp ecx, font_last_char
	jg .out
	; find glyph data: font_8x8 + (ch - font_first_char) * 8
	sub ecx, font_first_char
	shl ecx, 3				; * 8 bytes per glyph
	lea r10, [font_8x8]
	add r10, rcx			; r10 = ptr to this glyph's 8 row bytes
	; reject fully offscreen glyphs, cheaper than per-pixel clipping
	test edi, edi
	js .out
	cmp edi, WINDOW_W - DEBUG_GLYPH_W
	jg .out
	test esi, esi
	js .out
	cmp esi, WINDOW_H - DEBUG_GLYPH_H
	jg .out
	; compute fb pointer for (x,y)
	mov eax, esi
	imul eax, WINDOW_W
	add eax, edi
	shl rax, 2					; * 4 bytes per pixel
	lea r11, [framebuffer]
	add r11, rax				; r11 = fb ptr for this row

	mov r12d, 8					; 8 rows to draw
.row:
	movzx eax, byte [r10]		; load one row of the glyph (8 bits)
	test eax, eax
	jz .skip_row				; all bits zero = blank row, skip it

	; walk 8 bits, MSB first. if the bit is set, write the colour.
	mov r14, r11				; r14 = pixel write cursor
	mov r15d, eax				; r15d = the row byte
	mov ecx, 8
.bit:
	test r15d, 0x80				; check the top bit
	jz .nobit
	mov [r14], edx				; write colour pixel
.nobit:
	add r14, 4					; advance one pixel (4 bytes)
	shl r15d, 1					; shift next bit into position 7
	dec ecx
	jnz .bit

.skip_row:
	inc r10						; next glyph row byte
	add r11, FB_PITCH			; next framebuffer row
	dec r12d
	jnz .row

.out:
	pop r15
	pop r14
	pop r13
	pop r12
	pop rbx
	ret

;================================================================
; debug_print: draw a null-terminated string
;----------------------------------------------------------------
; handles '\n' (ASCII 10) by resetting x to starting column
; and advancing y by one glyph height (for future non-square fonts)
;----------------------------------------------------------------
; in: edi = x, esi = y, edx = ARGB colour, rcx = string pointer
;================================================================
debug_print:
	push rbx
	push r12
	push r13
	push r14
	push r15

	mov r12d, edi				; current x (advances per char)
	mov r13d, esi				; current y (advances on newline)
	mov r14d, edx				; colour (constant)
	mov r15, rcx				; string cursor
	mov ebx, edi				; remember the starting x for newlines
.loop:
	movzx eax, byte [r15]
	test al, al
	jz .done					; null terminator = stop

	cmp al, 10					; newline?
	je .newline

	; draw this character
	mov edi, r12d
	mov esi, r13d
	mov edx, r14d
	movzx ecx, al
	call debug_draw_glyph

	add r12d, DEBUG_GLYPH_W		; advance x by one glyph width
	jmp .next

.newline:
	mov r12d, ebx				; reset x to starting column
	add r13d, DEBUG_GLYPH_H		; advance y down a line
.next:
	inc r15						; next character
	jmp .loop

.done:
	pop r15
	pop r14
	pop r13
	pop r12
	pop rbx
	ret

;================================================================
; int_to_str: convert a signed 32bit int to ASCII
;----------------------------------------------------------------
; fills the buffer from right to left, as we extract digits w
; repeated div-by-10, which gives the least sig fig first
;
; returns a ptr to first char within the buffer
;
; C equiv:
;	char *int_to_str(int value, char *buf) {
;		buf[11] = '\0';
;		char *p = &buf[10];
;		int neg = (value < 0);
;		if (neg) value = -value;
;		if (value == 0) *p-- = '0';
;		while (value > 0) { *p-- = '0' + value % 10; value /= 10; }
;		if (neg) *p-- = '-';
;		return p + 1;
;	}
; tested in C, should give us INT_MIN+1(-2147483647) to abs of that
;----------------------------------------------------------------
; in:  edi = value, rsi = buffer ptr (needs >= 12 bytes)
;out: rax = ptr to first character of the string
;================================================================
int_to_str:
	push rbx
	push r12
	mov r12, rsi			; buffer base
	; start writing at the end (right-to-left)
	mov rax, rsi
	add rax, 11				; last position
	mov byte [rax], 0		; null terminator
	dec rax
	mov rbx, rax			; rbx = write cursor

	mov eax, edi
	xor r10d, r10d			; negative flag
	test eax, eax
	jns .conv
	neg eax					; make positive
	mov r10d, 1				; mark it was negative
.conv:
	; special case: value=0
	test eax, eax
	jnz .digits
	mov byte [rbx], '0'
	dec rbx
	jmp .digits_done

	; extract digits via repeated div/10
.digits:
	test eax, eax
	jz .digits_done
	xor edx, edx
	mov ecx, 10
	div ecx					; eax = quotient, edx = remainder
	add dl, '0'				; convert remainder to ASCII
	mov [rbx], dl
	dec rbx
	jmp .digits
.digits_done:
	; add - if negative
	test r10d, r10d
	jz .no_sign
	mov byte [rbx], '-'
	dec rbx
.no_sign:
	inc rbx					; point at the first written char
	mov rax, rbx			; return it
	pop r12
	pop rbx
	ret

;================================================================
; debug_print_int: draw a signed integer on screen
;----------------------------------------------------------------
; in: edi = x, esi = y, edx = ARGB colour, ecx = value
;================================================================
debug_print_int:
	push rbx
	push r12
	push r13
	push r14

	mov r12d, edi			; save x
	mov r13d, esi			; save y
	mov r14d, edx			; save colour

	; convert the integer to a string
	mov edi, ecx
	lea rsi, [int_buf]
	call int_to_str
	mov rcx, rax			; rcx = string pointer

	; draw it
	mov edi, r12d
	mov esi, r13d
	mov edx, r14d
	call debug_print

	pop r14
	pop r13
	pop r12
	pop rbx
	ret

;================================================================
; debug_print_label: helper, for now used for FPS
;
; draws "label: integerastext".  returns x cursor after end (px)
;----------------------------------------------------------------
;  in:	edi = x, esi = y, edx = ARGB colour,
;		rcx = label string pointer (no trailing ": " needed),
;		r8d = integer value
;
; out:	eax = x pixel value past final right edge
;================================================================
debug_print_label_int:
	push rbx
	push r12
	push r13
	push r14
	push r15

	mov r12d, edi		; current x
	mov r13d, esi		; y
	mov r14d, edx		; colour
	mov r15d, r8d		; value to print
	mov rbx, rcx		; label string

	; draw the label text
	mov edi, r12d
	mov esi, r13d
	mov edx, r14d
	mov rcx, rbx
	call debug_print

	; advance x by the label's pixel width
	mov rdi, rbx
	call strlen_simple			; eax = length in chars
	imul eax, DEBUG_GLYPH_W		; * 8 pixels per char
	add r12d, eax

	; draw ": " separator (two individual chhars)
	mov edi, r12d
	mov esi, r13d
	mov edx, r14d
	mov ecx, ':'
	call debug_draw_glyph
	add r12d, DEBUG_GLYPH_W

	mov edi, r12d
	mov esi, r13d
	mov edx, r14d
	mov ecx, ' '
	call debug_draw_glyph
	add r12d, DEBUG_GLYPH_W

	; draw the int value as chars
	mov edi, r12d
	mov esi, r13d
	mov edx, r14d
	mov ecx, r15d
	call debug_print_int

	; return the end x
	; measuring by converting again then measuring str len
	mov edi, r15d
	lea rsi, [int_buf]
	call int_to_str
	mov rdi, rax
	call strlen_simple
	imul eax, DEBUG_GLYPH_W
	add r12d, eax

	mov eax, r12d	; return final x's position
	pop r15
	pop r14
	pop r13
	pop r12
	pop rbx
	ret

;================================================================
; strlen_simple: count bytes in null-terminated str
;----------------------------------------------------------------
;  in:	rdi = string ptr
; out:	eax = length (not counting the null)
;================================================================
strlen_simple:
	xor eax, eax
.loop:
	cmp byte [rdi + rax], 0 ;match?
	je .done
	inc eax ; ++
	jmp .loop ; elegant!
.done:
	ret

;================================================================
; debug_log: append a line to log ring bufer
; 
; 1. copies the str into next ring buffer slot
; 2. truncates to LOG_LINE_LENGTH-1
; 3. advances ring head & bumps count (capped to LOG_LINES)
;----------------------------------------------------------------
;  in:	rdi = null-terminated string ptr
;================================================================
debug_log:
	push rbx
	push r12

	; dest = log_buffer + log_head * LOG_LINE_LENGTH
	mov eax, [log_head]
	mov ecx, LOG_LINE_LENGTH
	mul ecx
	lea rbx, [log_buffer]
	add rbx, rax				; rbx = destination line

	; copy chars until null/till we've written LOG_LINE_LENGTH-1
	mov r12d, LOG_LINE_LENGTH - 1
	mov rsi, rdi				; source
	mov rdi, rbx				; dest
.copy:
	test r12d, r12d
	jz .terminate				; hit max length
	movzx eax, byte [rsi]
	mov [rdi], al
	test al, al
	jz .done					; hit null terminator
	inc rsi
	inc rdi
	dec r12d
	jmp .copy
.terminate:
	mov byte [rdi], 0			; force null-terminate if we truncated
.done:
	; advance head, wrapping around
	mov eax, [log_head]
	inc eax
	cmp eax, LOG_LINES
	jl .no_wrap
	xor eax, eax				; wrap to 0
.no_wrap:
	mov [log_head], eax

	; count++, capped at LOG_LINES
	mov eax, [log_count]
	cmp eax, LOG_LINES
	jge .count_capped
	inc eax
	mov [log_count], eax
.count_capped: ;end
	pop r12
	pop rbx
	ret

;================================================================
; debug_log_label_int: log "label: int"
;----------------------------------------------------------------
; similar to the label: int printer, builds in stack scratch buffer
; then passes to debug_log
;----------------------------------------------------------------
; in: rdi = label pointer, esi = int value
;================================================================
debug_log_label_int:
	push rbp
	mov rbp, rsp
	sub rsp, 80				; scratch buffer on the stack
	push rbx
	push r12

	; copy label into scratch buffer @ [rbp-72]
	mov r12, rdi
	lea rbx, [rbp-72]
.copy_label:
	movzx eax, byte [r12]
	mov [rbx], al
	test al, al
	jz .label_done
	inc r12
	inc rbx
	jmp .copy_label
.label_done:
	; append ": "
	mov byte [rbx], ':'
	inc rbx
	mov byte [rbx], ' '
	inc rbx

	; convert the int to ascii & append it
	mov edi, esi
	lea rsi, [int_buf]
	call int_to_str 		; rax = pointer to digit string
.copy_digits:
	movzx ecx, byte [rax]
	mov [rbx], cl
	test cl, cl
	jz .send
	inc rax
	inc rbx
	jmp .copy_digits

.send:
	lea rdi, [rbp-72]
	call debug_log

	pop r12
	pop rbx
	leave
	ret

;================================================================
; debug_render_log: draw log lines @ bottom of scren
;----------------------------------------------------------------
; renders oldest at top like a console...TODO: make
; oldest should be @ [(head - count + LOG_LINES) % LOG_LINES)]
; iterating count forward till newest
;================================================================
debug_render_log:
	push rbx
	push r12
	push r13
	push r14
	push r15

	mov r12d, [log_count]
	test r12d, r12d
	jz .done				; nothing logged yet

	; compute the index of the oldest visible slot
	; first_slot = (head - count + LOG_LINES) % LOG_LINES
	mov eax, [log_head]
	sub eax, r12d
	add eax, LOG_LINES
	xor edx, edx
	mov ecx, LOG_LINES
	div ecx					; edx = first slot index
	mov r13d, edx			; r13 = current slot

	; y pos: glyph-h's above the bottom for now
	mov r14d, WINDOW_H - DEBUG_GLYPH_H * LOG_LINES - 4
	mov r15d, r12d			; lines remaining
.line:
	test r15d, r15d
	jz .done

	; line ptr = log_buffer + slot * LOG_LINE_LENGTH
	mov eax, r13d
	mov ecx, LOG_LINE_LENGTH
	mul ecx
	lea rbx, [log_buffer]
	add rbx, rax

	; print the text
	mov edi, 4				; x = 4, small left margin
	mov esi, r14d
	mov edx, 0xFF000000		; black
	mov rcx, rbx
	call debug_print

	add r14d, DEBUG_GLYPH_H	; advance y down one line

	; advance slot, wrapping
	inc r13d
	cmp r13d, LOG_LINES
	jl .no_wrap
	xor r13d, r13d
.no_wrap:
	dec r15d
	jmp .line

.done:
	pop r15
	pop r14
	pop r13
	pop r12
	pop rbx
	ret

; -------------------------- Utilities -------------------------------

;================================================================
; debug_toggle: flip HUD visibility flag
;================================================================
debug_toggle:
	mov al, [debug_hud_enabled]
	xor al, 1 ; 0->1, 1->0, neat and should be faster than 1-
	mov [debug_hud_enabled], al
	ret

;================================================================
; is_debug_hud_enabled: visible?
; out: eax = 1 if enabled, else 0
;================================================================
is_debug_hud_enabled:
	movzx eax, byte [debug_hud_enabled]
	ret

%endif
