; particles.inc.asm - particle engine for vfx
;----------------------------------------------------------------
; pool of PARTICLE_MAX particles, all kept SOA
;
; each particle has:
;	x, y		Q16.16 fixed-point world coords
;	vx, vy		Q16.16 velocity (pixels-per-frame)
;	life		frames remaining (0 = dead)
;	life_max	starting life (used for fade ratio)
;	flags		bit 0 = active, bit 1 = gravity-on, bit 2 = rect
;				bit 3 = world-space (else screen-space)
;				bit 4 = wind-on (NOT IN USE)
;	colour_a	starting ARGB
;	colour_b	end ARGB (for lerp)
;
; presets so far:
;	burst_chop		wood chips + green leaves
;	burst_dig		stone shards + grey dust
;	burst_hit		directional blood spray + bright impact flash
;	burst_smoke		pale grey rects
;	burst_ring		primitive: N particles evenly around a circle
;	burst_splash	water droplets in a ring + central white flash
;
; the *_dir variants take a FACE_* and bias velocity along/across
; the facing axis
;----------------------------------------------------------------

%ifndef PARTICLES_INC
%define PARTICLES_INC

%define PARTICLE_MAX			400

; flags
%define P_FLAG_ACTIVE			0x01
%define P_FLAG_GRAVITY			0x02
%define P_FLAG_RECT				0x04	; else single pixel
%define P_FLAG_WORLD_SPACE		0x08	; else screen-space
%define P_FLAG_WIND				0x10	; tried but NOT IN USE atm
%define P_FLAG_DITHER_FADE		0x20	; bayer-dither out using
										; lerped alpha as threshold
%define P_FLAG_SETTLE			0x40	; zero vy near end of life,
										; so things look like they
										; hit the ground and roll

; gravity per frame
%define P_GRAVITY_Q				0x00002000

; rect particle size
%define P_RECT_W				2
%define P_RECT_H				2

section .data
	log_msg_particles_off	db "particles off", 0
	log_msg_particles_on	db "particles on", 0

	; unit-circle directions for the ring primitive.  8 evenly spaced
	; vectors at Q16.16 scale.  if caller asks for >8 we step around
	; by reusing entries with a bit of phase variance from rng_next
	align 4
	ring_dirs:
		; (cos, sin) * 0x10000 for 45degs
		; generated by scripts/ring.py
		dd 0x10000, 0x00000		; 0
		dd 0x0B504, 0x0B504		; 45
		dd 0x00000, 0x10000		; 90
		dd -0x0B504, 0x0B504	; 135
		dd -0x10000, 0x00000	; 180
		dd -0x0B504, -0x0B504	; 225
		dd 0x00000, -0x10000	; 270
		dd 0x0B504, -0x0B504	; 315


section .bss
	alignb 4
	; struct-of-arrays
	p_x			resd PARTICLE_MAX
	p_y			resd PARTICLE_MAX
	p_vx		resd PARTICLE_MAX
	p_vy		resd PARTICLE_MAX
	p_col_a		resd PARTICLE_MAX
	p_col_b		resd PARTICLE_MAX
	p_life		resw PARTICLE_MAX
	p_life_max	resw PARTICLE_MAX
	p_flags		resb PARTICLE_MAX

	particle_count			resd 1
	particle_next_hint		resd 1
	particle_enabled		resb 1

section .text

;================================================================
; particles_init: zero all particles
;================================================================
particles_init:
	push rdi
	push rcx
	lea rdi, [p_flags]
	mov ecx, PARTICLE_MAX
	xor eax, eax
	rep stosb
	mov dword [particle_count], 0
	mov dword [particle_next_hint], 0
	mov byte [particle_enabled], 1
	pop rcx
	pop rdi
	ret

;================================================================
; particles_toggle: console "particles" command
; NOT CURRENTLY USED
;================================================================
particles_toggle:
	xor byte [particle_enabled], 1
	cmp byte [particle_enabled], 0
	je .off
	lea rdi, [log_msg_particles_on]
	jmp .log
.off:
	lea rdi, [log_msg_particles_off]
.log:
	call debug_log
	ret

;================================================================
; particle_find_slot: scan p_flags for inactive slot
;----------------------------------------------------------------
;out: eax = slot index, or -1 if pool full
;================================================================
particle_find_slot:
	push rbx
	mov ebx, [particle_next_hint]
	mov ecx, PARTICLE_MAX
.next:
	test ecx, ecx
	jz .full

	lea rdx, [p_flags]
	movzx eax, byte [rdx + rbx]
	test eax, P_FLAG_ACTIVE
	jz .found

	inc ebx
	cmp ebx, PARTICLE_MAX
	jl .nowrap
	xor ebx, ebx
.nowrap:
	dec ecx
	jmp .next

.found:
	mov eax, ebx
	inc ebx
	cmp ebx, PARTICLE_MAX
	jl .ok
	xor ebx, ebx
.ok:
	mov [particle_next_hint], ebx
	pop rbx
	ret
.full:
	mov eax, -1
	pop rbx
	ret

;================================================================
; particle_spawn: low-level spawn
;----------------------------------------------------------------
; in:  edi = x, esi = y
;	   edx = vx, ecx = vy (all Q16.16)
;	   r8d = colour_a, r9d = colour_b
;	   [rsp+8] = life (u16, in low half of qword)
;	   [rsp+16] = flags (u8, in low byte of qword)
;----------------------------------------------------------------
; if pool is full, silently drops the request
;================================================================
particle_spawn:
	cmp byte [particle_enabled], 0
	je .out
	push rbx
	push r12
	push r13
	push r14
	push r15

	mov r12d, edi
	mov r13d, esi
	mov r14d, edx
	mov r15d, ecx
	push r8
	push r9

	call particle_find_slot
	test eax, eax
	js .pop_out

	mov ebx, eax

	pop r9
	pop r8

	; pos/vel
	lea rdx, [p_x]
	mov [rdx + rbx*4], r12d
	lea rdx, [p_y]
	mov [rdx + rbx*4], r13d
	lea rdx, [p_vx]
	mov [rdx + rbx*4], r14d
	lea rdx, [p_vy]
	mov [rdx + rbx*4], r15d
	lea rdx, [p_col_a]
	mov [rdx + rbx*4], r8d
	lea rdx, [p_col_b]
	mov [rdx + rbx*4], r9d

	; life: caller pushed 2 qwords before the call.
	; after our 5 prologue pushes + return addr,
	; life is at [rsp+48], flags at [rsp+56]
	mov eax, [rsp + 48]
	lea rdx, [p_life]
	mov [rdx + rbx*2], ax
	lea rdx, [p_life_max]
	mov [rdx + rbx*2], ax

	mov eax, [rsp + 56]
	or eax, P_FLAG_ACTIVE
	lea rdx, [p_flags]
	mov [rdx + rbx], al

	inc dword [particle_count]

	pop r15
	pop r14
	pop r13
	pop r12
	pop rbx
	ret

.pop_out:
	pop r9
	pop r8
	pop r15
	pop r14
	pop r13
	pop r12
	pop rbx
.out:
	ret

;================================================================
; particles_tick: integrate every active particle one frame
;================================================================
particles_tick:
	cmp byte [particle_enabled], 0
	je .out

	push rbx
	push r12

	xor ebx, ebx
.next:
	cmp ebx, PARTICLE_MAX
	jge .done

	lea rdx, [p_flags]
	movzx eax, byte [rdx + rbx]
	test eax, P_FLAG_ACTIVE
	jz .skip
	mov r12d, eax

	; decrement life
	lea rdx, [p_life]
	movzx eax, word [rdx + rbx*2]
	dec eax
	mov [rdx + rbx*2], ax
	test ax, ax
	jnz .alive

	; died - mark inactive
	lea rdx, [p_flags]
	mov byte [rdx + rbx], 0
	dec dword [particle_count]
	jmp .skip

.alive:
	; integrate pos
	lea rdx, [p_vx]
	mov eax, [rdx + rbx*4]
	lea rdx, [p_x]
	add [rdx + rbx*4], eax

	lea rdx, [p_vy]
	mov eax, [rdx + rbx*4]
	lea rdx, [p_y]
	add [rdx + rbx*4], eax

	; gravity
	test r12d, P_FLAG_GRAVITY
	jz .nograv
	lea rdx, [p_vy]
	add dword [rdx + rbx*4], P_GRAVITY_Q
.nograv:

	; settle: in the last 20% of life, kill vy and damp vx so the
	; particle looks like it hit the floor and rolled to a stop.
	; using life * 5 < life_max as the cheap "<20% remaining" check
	test r12d, P_FLAG_SETTLE
	jz .nosettle
	lea rdx, [p_life]
	movzx eax, word [rdx + rbx*2]
	imul eax, 5
	lea rdx, [p_life_max]
	movzx ecx, word [rdx + rbx*2]
	cmp eax, ecx
	jge .nosettle
	lea rdx, [p_vy]
	mov dword [rdx + rbx*4], 0
	; halve vx each frame in this phase - kinda like a "rolling stop"
	lea rdx, [p_vx]
	mov eax, [rdx + rbx*4]
	sar eax, 1
	mov [rdx + rbx*4], eax
.nosettle:

	; wind wip with weather.inc.asm, NOT CURRENTLY USED
	test r12d, P_FLAG_WIND
	jz .nowind
	; mov eax, [wind_vx_q]
	; sar eax, 4
	; lea rdx, [p_vx]
	; add [rdx + rbx*4], eax
	; mov eax, [wind_vy_q]
	; sar eax, 4
	; lea rdx, [p_vy]
	; add [rdx + rbx*4], eax
.nowind:

.skip:
	inc ebx
	jmp .next
.done:
	pop r12
	pop rbx
.out:
	ret

;================================================================
; lerp_byte_q
; in:  edi = a, esi = b, edx = t (0..256)
;out:  eax = a + (b - a) * t / 256, clamped 0..255
;================================================================
lerp_byte_q:
	mov eax, esi
	sub eax, edi
	imul eax, edx
	sar eax, 8
	add eax, edi
	test eax, eax
	jns .lo_ok
	xor eax, eax
.lo_ok:
	cmp eax, 255
	jle .hi_ok
	mov eax, 255
.hi_ok:
	ret

;================================================================
; particles_draw: render every active particle
;================================================================
particles_draw:
	cmp byte [particle_enabled], 0
	je .out
	cmp dword [particle_count], 0
	je .out

	push rbx
	push r12
	push r13
	push r14
	push r15
	sub rsp, 16

	xor ebx, ebx
.next:
	cmp ebx, PARTICLE_MAX
	jge .done

	lea rdx, [p_flags]
	movzx eax, byte [rdx + rbx]
	test eax, P_FLAG_ACTIVE
	jz .skip
	mov r15d, eax ; flags

	; screen pos
	lea rdx, [p_x]
	mov eax, [rdx + rbx*4]
	sar eax, 16
	test r15d, P_FLAG_WORLD_SPACE
	jz .has_x
	sub eax, [camera_x]
.has_x:
	mov r12d, eax

	lea rdx, [p_y]
	mov eax, [rdx + rbx*4]
	sar eax, 16
	test r15d, P_FLAG_WORLD_SPACE
	jz .has_y
	sub eax, [camera_y]
.has_y:
	mov r13d, eax

	; bounds
	test r12d, r12d
	js .skip
	test r13d, r13d
	js .skip
	cmp r12d, WINDOW_W
	jge .skip
	cmp r13d, WINDOW_H
	jge .skip

	; colour lerp
	lea rdx, [p_life_max]
	movzx ecx, word [rdx + rbx*2]
	test ecx, ecx
	jz .skip
	lea rdx, [p_life]
	movzx edi, word [rdx + rbx*2]

	mov eax, ecx
	sub eax, edi
	shl eax, 8
	cdq
	idiv ecx
	mov r14d, eax		; t

	lea rdx, [p_col_a]
	mov ecx, [rdx + rbx*4]
	lea rdx, [p_col_b]
	mov edx, [rdx + rbx*4]
	mov [rsp], ecx
	mov [rsp+4], edx

	; A
	mov edi, ecx
	shr edi, 24
	and edi, 0xFF
	mov esi, edx
	shr esi, 24
	and esi, 0xFF
	mov edx, r14d
	call lerp_byte_q
	mov [rsp+8], eax

	mov ecx, [rsp]
	mov edx, [rsp+4]
	mov edi, ecx
	shr edi, 16
	and edi, 0xFF
	mov esi, edx
	shr esi, 16
	and esi, 0xFF
	mov edx, r14d
	call lerp_byte_q
	mov [rsp+9], al

	mov ecx, [rsp]
	mov edx, [rsp+4]
	mov edi, ecx
	shr edi, 8
	and edi, 0xFF
	mov esi, edx
	shr esi, 8
	and esi, 0xFF
	mov edx, r14d
	call lerp_byte_q
	mov [rsp+10], al

	mov ecx, [rsp]
	mov edx, [rsp+4]
	mov edi, ecx
	and edi, 0xFF
	mov esi, edx
	and esi, 0xFF
	mov edx, r14d
	call lerp_byte_q
	mov [rsp+11], al

	movzx eax, byte [rsp+8]
	shl eax, 24
	movzx ecx, byte [rsp+9]
	shl ecx, 16
	or eax, ecx
	movzx ecx, byte [rsp+10]
	shl ecx, 8
	or eax, ecx
	movzx ecx, byte [rsp+11]
	or eax, ecx
	mov r14d, eax

	; dither fade flag on?: lerp alphha/bayer @ screen pos
	; below threshold - skip entirely, fade to nothing. on pass, 
	; force alpha 0xFF so we draw fully opaque
	test r15d, P_FLAG_DITHER_FADE
	jz .nodither
	mov edi, r12d
	and edi, 3				; x % 4
	mov esi, r13d
	and esi, 3				; y % 4
	shl esi, 2				; y * 4
	add edi, esi			; bayer idx 0..15
	lea rdx, [bayer4x4edged]
	movzx edx, byte [rdx + rdi]
	movzx ecx, byte [rsp+8]	; lerped alpha
	cmp ecx, edx
	jl .skip				; under threshold, drop this pixel
	or r14d, 0xFF000000		; otherwise draw opaque
.nodither:

	test r15d, P_FLAG_RECT
	jnz .rect
	mov edi, r12d
	mov esi, r13d
	mov edx, r14d
	call plot_pixel
	jmp .skip
.rect:
	mov edi, r12d
	mov esi, r13d
	mov edx, P_RECT_W
	mov ecx, P_RECT_H
	mov r8d, r14d
	call fill_rect

.skip:
	inc ebx
	jmp .next
.done:
	add rsp, 16
	pop r15
	pop r14
	pop r13
	pop r12
	pop rbx
.out:
	ret

;================================================================
; rng_smallrange: get a small int in [-half, +half]
; in: edi = half (range)
;out: eax = signed value
; clb: rcx, rdx
;================================================================
rng_smallrange:
	push rdi
	mov eax, edi
	shl eax, 1
	inc eax
	mov edi, eax		; range = 2*half + 1
	call rng_range		; eax in [0, range)
	pop rdi
	sub eax, edi
	ret

;================================================================
; particle_burst_ring: N particles radiating outward from (x,y)
;----------------------------------------------------------------
; main primitive.  picks a direction per particle from
; the 8-entry ring_dirs table, scale by speed_q for outward
; velocity, optional gravity for falling droplets etc
;
; if count > 8, we step around the table modulo 8, with a small
; rng jitter on the index
;----------------------------------------------------------------
; in:  edi = x			esi = y
;	   edx = count		ecx = speed_q
;	   r8d = col_a		r9d = col_b
;	   [rsp+8] = life
;	   [rsp+16] = flags (extra flags or 0)
;----------------------------------------------------------------
; stack layout while running:
;	[rsp+0]	 col_a
;	[rsp+4]	 col_b
;	[rsp+8]	 life
;	[rsp+12] extra flags
;	[rsp+16] loop counter
;	[rsp+20] padding
;	then pushes rbp/r15..rbx + ret + caller args at rsp+88,+96
;================================================================
particle_burst_ring:
	push rbx
	push r12
	push r13
	push r14
	push r15
	push rbp
	sub rsp, 24

	mov r12d, edi				; cx (px)
	mov r13d, esi				; cy (px)
	mov r14d, edx				; count
	mov r15d, ecx				; speed_q

	mov [rsp], r8d
	mov [rsp+4], r9d
	; 6 pushes (48) + sub 24 = 72 below entry, plus ret(8) + life(8) = 80
	mov eax, [rsp + 80]
	mov [rsp+8], eax			; life
	mov eax, [rsp + 88]
	mov [rsp+12], eax			; extra flags
	mov dword [rsp+16], 0		; iter

.loop:
	mov ebp, [rsp+16]
	cmp ebp, r14d
	jge .done

	; pick angle index =  (iter + jitter) & 7
	mov eax, ebp
	shl eax, 3
	cdq
	idiv r14d					; eax = iter*8/count
	mov ebx, eax

	call rng_next
	and eax, 1
	add ebx, eax
	and ebx, 7

	lea rax, [ring_dirs]
	shl ebx, 3
	mov ecx, [rax + rbx]		; ux Q16.16
	mov edx, [rax + rbx + 4]	; uy Q16.16

	; vx = (ux * speed_q) >> 16
	movsxd rax, ecx
	movsxd rdi, r15d
	imul rax, rdi
	sar rax, 16
	mov ebx, eax				; vx in ebx (saved)

	movsxd rax, edx
	movsxd rdi, r15d
	imul rax, rdi
	sar rax, 16
	mov ebp, eax				; vy in ebp (saved)

	; pos in Q16.16 with sub-pixel jitter
	call rng_next
	mov ecx, eax
	and ecx, 0x3FFFF
	sub ecx, 0x1FFFF
	mov edi, r12d
	shl edi, 16
	add edi, ecx

	call rng_next
	mov ecx, eax
	and ecx, 0x3FFFF
	sub ecx, 0x1FFFF
	mov esi, r13d
	shl esi, 16
	add esi, ecx

	mov edx, ebx				; vx
	mov ecx, ebp				; vy
	mov r8d, [rsp]
	mov r9d, [rsp+4]

	; push spawn's stack args.  use the values from our scratch
	; slots BEFORE we push (so offsets stay sane)
	mov eax, [rsp+12]			; extra flags
	push rax
	mov eax, [rsp+16]			; life
	push rax

	call particle_spawn
	add rsp, 16

	inc dword [rsp+16]
	jmp .loop

.done:
	add rsp, 24
	pop rbp
	pop r15
	pop r14
	pop r13
	pop r12
	pop rbx
	ret

;================================================================
; preset bursts
;----------------------------------------------------------------
; all take (x_px, y_px) in WORLD pixel coords as int32.  the
; conversion to Q16.16 happens inside particle_spawn calls below
;
; some take a FACE_DOWN/UP/LEFT/RIGHT arg in edx to bias the spray
;================================================================

;================================================================
; particle_burst_chop: bits of wood/leaves
;----------------------------------------------------------------
; in: edi = x_px, esi = y_px, edx = face (of chopper)
;================================================================
particle_burst_chop:
	push rbx
	push r12
	push r13
	push r14
	push r15
	push rbp
	sub rsp, 8

	mov r12d, edi ; x
	mov r13d, esi ; y
	mov r14d, edx ; face

	; --- chips: 10 of them ---
	mov ebp, 10
.chip:
	; outward dir = -facing
	; facing: 0=down, 1=up, 2=left, 3=right
	; bias: chip vx = lateral noise; chip vy = small upward + noise
	mov edi, 2				; rng_smallrange(2) -> -2..2
	call rng_smallrange
	; treating this as "perpendicular spread" component
	mov ebx, eax			; perp

	mov edi, 2
	call rng_smallrange
	; "back along -facing" component
	add eax, 3				; bias outward, now 1..5
	mov r15d, eax			; outward

	; randomise the brown shade BEFORE building vx/vy..
	; rng_next clobbers rcx, and we put vy in ecx below
	; shade goes into r10d which is callee-clobbered/free now
	call rng_next
	and eax, 0x1F
	mov r10d, 0xFF804020
	sub r10d, eax

	; build vx, vy
	xor edi, edi			; will be vx
	xor esi, esi			; will be vy

	cmp r14d, 0				; FACE_DOWN  -> we're south of tree
	jne .nf_down
	mov esi, r15d			; chips fly DOWN (south, away from tree to person cohpping)
	shl esi, 14
	mov edi, ebx
	shl edi, 14
	; add upward bias regardless so chips arc up
	sub esi, 0x6000
	jmp .have_v
.nf_down:
	cmp r14d, 1				; FACE_UP
	jne .nf_up
	mov esi, r15d
	neg esi
	shl esi, 14
	mov edi, ebx
	shl edi, 14
	sub esi, 0x6000			; arc
	jmp .have_v
.nf_up:
	cmp r14d, 2				; FACE_LEFT
	jne .nf_left
	mov edi, r15d
	neg edi
	shl edi, 14
	mov esi, ebx
	shl esi, 14
	sub esi, 0x6000			; arc up
	jmp .have_v
.nf_left:
	mov edi, r15d			; FACE_RIGHT
	shl edi, 14
	mov esi, ebx
	shl esi, 14
	sub esi, 0x6000
.have_v:
	mov edx, edi			; vx
	mov ecx, esi			; vy

	mov edi, r12d			; pos x
	shl edi, 16
	mov esi, r13d			; pos y
	shl esi, 16

	mov r8d, r10d			; col_a
	mov r9d, 0xFF602000		; col_b

	push qword (P_FLAG_GRAVITY | P_FLAG_RECT | P_FLAG_WORLD_SPACE | P_FLAG_SETTLE)
	push qword 18
	call particle_spawn
	add rsp, 16

	dec ebp
	jnz .chip

	; --- leaves: 3 green rect particles.  same directional arc as
	; chips but a bit slower and lower-arc
	mov ebp, 3
.leaf:
	mov edi, 2
	call rng_smallrange
	mov ebx, eax			; perp

	mov edi, 2
	call rng_smallrange
	add eax, 2				; outward 0..4
	mov r15d, eax

	; green shade set BEFORE setting up vx/vy.  rng_next
	; clobbers rcx, and vy lives in ecx for the spawn call
	call rng_next
	mov r10d, eax
	and r10d, 0x1F
	add r10d, 0xFF008000		; col_a leaf green

	; same facing dispatch as chips above,
	; but shifted 13 (half speed) and no upward kick
	xor edi, edi
	xor esi, esi
	cmp r14d, 0
	jne .lf_down
	mov esi, r15d
	shl esi, 13
	mov edi, ebx
	shl edi, 13
	jmp .lf_have
.lf_down:
	cmp r14d, 1
	jne .lf_up
	mov esi, r15d
	neg esi
	shl esi, 13
	mov edi, ebx
	shl edi, 13
	jmp .lf_have
.lf_up:
	cmp r14d, 2
	jne .lf_left
	mov edi, r15d
	neg edi
	shl edi, 13
	mov esi, ebx
	shl esi, 13
	jmp .lf_have
.lf_left:
	mov edi, r15d
	shl edi, 13
	mov esi, ebx
	shl esi, 13
.lf_have:
	mov edx, edi
	mov ecx, esi

	mov edi, r12d
	shl edi, 16
	mov esi, r13d
	shl esi, 16

	mov r8d, r10d			; col_a
	mov r9d, 0xFF002000		; col_b: darker green

	push qword (P_FLAG_RECT | P_FLAG_WORLD_SPACE | P_FLAG_GRAVITY | P_FLAG_SETTLE)
	push qword 22
	call particle_spawn
	add rsp, 16

	dec ebp
	jnz .leaf

	add rsp, 8
	pop rbp
	pop r15
	pop r14
	pop r13
	pop r12
	pop rbx
	ret

;================================================================
; particle_burst_dig: stone bits & dust, no dir	
;----------------------------------------------------------------
; in: edi = x_px, esi = y_px
;================================================================
particle_burst_dig:
	push rbx
	push r12
	push r13
	push rbp
	sub rsp, 8

	mov r12d, edi
	mov r13d, esi

	; --- shards ---
	mov ebp, 6
.shard:
	mov edi, 3
	call rng_smallrange		; eax in -3..3
	mov ebx, eax

	mov edi, 3
	call rng_smallrange		; eax in -3..3
	sub eax, 3				; -6..0, strong upward bias

	mov edx, ebx
	shl edx, 14
	mov ecx, eax
	shl ecx, 14

	mov edi, r12d
	shl edi, 16
	mov esi, r13d
	shl esi, 16

	mov r8d, 0xFFC0C0C0		; greys from stone walls in tiles.ppm
	mov r9d, 0xFF606060

	push qword (P_FLAG_GRAVITY | P_FLAG_RECT | P_FLAG_WORLD_SPACE |  P_FLAG_SETTLE)
	push qword 22
	call particle_spawn
	add rsp, 16

	dec ebp
	jnz .shard

	; --- dust pixels ---
	mov ebp, 10
.dust:
	mov edi, 4
	call rng_smallrange		; -4..4
	mov ebx, eax

	mov edi, 3
	call rng_smallrange		; -3..3
	sub eax, 2				; -5..1

	mov edx, ebx
	shl edx, 12				; half the previous velocity scale
	mov ecx, eax
	shl ecx, 12

	mov edi, r12d
	shl edi, 16
	mov esi, r13d
	shl esi, 16

	mov r8d, 0xFF808080		; grey opaque
	mov r9d, 0x00202020		; fade

	push qword (P_FLAG_WORLD_SPACE | P_FLAG_DITHER_FADE)
	push qword 24
	call particle_spawn
	add rsp, 16

	dec ebp
	jnz .dust

	add rsp, 8
	pop rbp
	pop r13
	pop r12
	pop rbx
	ret

;================================================================
; particle_burst_hit: directional blood spray + impact flash
;----------------------------------------------------------------
; in: edi = x_px, esi = y_px, edx = face (of attacker)
;================================================================
particle_burst_hit:
	push rbx
	push r12
	push r13
	push r14
	push r15
	push rbp

	mov r12d, edi
	mov r13d, esi
	mov r14d, edx ; face

	; --- impact flash: 4 white sparks, very short ---
	mov ebp, 4
.flash:
	mov edi, 6
	call rng_smallrange
	mov ebx, eax

	mov edi, 6
	call rng_smallrange

	mov edx, ebx
	shl edx, 14
	mov ecx, eax
	shl ecx, 14

	mov edi, r12d
	shl edi, 16
	mov esi, r13d
	shl esi, 16

	mov r8d, 0xFFFFFFFF		; white
	mov r9d, 0x40FFC080		; warm fade

	push qword P_FLAG_WORLD_SPACE
	push qword 6
	call particle_spawn
	add rsp, 16

	dec ebp
	jnz .flash

	; --- blood: 8 droplets biased along facing direction ---
	mov ebp, 8
.blood:
	mov edi, 3
	call rng_smallrange		; -3..3
	mov ebx, eax			; perp

	mov edi, 2
	call rng_smallrange		; -2..2
	add eax, 3				; outward 1..5
	mov r15d, eax			; temp (stored in prologue)

	; same dispatch as chop, but along facing (not opposite)
	xor edi, edi
	xor esi, esi
	cmp r14d, 0				; FACE_DOWN
	jne .bh_down
	mov esi, r15d
	shl esi, 14
	mov edi, ebx
	shl edi, 14
	sub esi, 0x7000			; gentle upward arc
	jmp .bh_have
.bh_down:
	cmp r14d, 1				; FACE_UP
	jne .bh_up
	mov esi, r15d
	neg esi
	shl esi, 14
	mov edi, ebx
	shl edi, 14
	sub esi, 0x7000
	jmp .bh_have
.bh_up:
	cmp r14d, 2				; FACE_LEFT
	jne .bh_left
	mov edi, r15d
	neg edi
	shl edi, 14
	mov esi, ebx
	shl esi, 14
	sub esi, 0x7000
	jmp .bh_have
.bh_left:
	mov edi, r15d			; FACE_RIGHT
	shl edi, 14
	mov esi, ebx
	shl esi, 14
	sub esi, 0x7000
.bh_have:
	mov edx, edi
	mov ecx, esi

	mov edi, r12d
	shl edi, 16
	mov esi, r13d
	shl esi, 16

	mov r8d, 0xFFC00000		; bright blood
	mov r9d, 0xFF800000		; dark fade

	push qword (P_FLAG_GRAVITY | P_FLAG_WORLD_SPACE | P_FLAG_RECT)
	push qword 22
	call particle_spawn
	add rsp, 16

	dec ebp
	jnz .blood

	pop rbp
	pop r15
	pop r14
	pop r13
	pop r12
	pop rbx
	ret

;================================================================
; particle_burst_splash: water droplets in a radial ring + a
; bright central flash dot
;----------------------------------------------------------------
; in: edi = x_px, esi = y_px
;----------------------------------------------------------------
; uses burst_ring as the primitive.  droplets get gravity so they
; arc back down.  a brief white pixel marks the impact
;================================================================
particle_burst_splash:
	push rbx
	push r12
	push r13
	push rbp
	sub rsp, 8
	mov r12d, edi
	mov r13d, esi

	; --- 3 white foam sparks ---
	mov ebp, 3
.flash:
	mov edi, 2
	call rng_smallrange		; -2..2
	mov ebx, eax

	mov edi, 1
	call rng_smallrange
	sub eax, 2				; -3..-1, biased up

	mov edx, ebx
	shl edx, 13
	mov ecx, eax
	shl ecx, 13

	mov edi, r12d
	shl edi, 16
	mov esi, r13d
	shl esi, 16

	mov r8d, 0xFFFFFFFF		; pure white
	mov r9d, 0xFFC0E8FF		; fade to pale blue

	push qword (P_FLAG_RECT | P_FLAG_WORLD_SPACE | P_FLAG_GRAVITY)
	push qword 10
	call particle_spawn
	add rsp, 16

	dec ebp
	jnz .flash

	; --- ring of 6 1px droplets ---
	mov edi, r12d
	mov esi, r13d
	mov edx, 6				; count
	mov ecx, 0x08000		; speed_q
	mov r8d, 0xFFFFFFFF		; white
	mov r9d, 0xFFA8D8FF		;  blue
	push qword (P_FLAG_GRAVITY | P_FLAG_WORLD_SPACE)
	push qword 10			; life
	call particle_burst_ring
	add rsp, 16

	add rsp, 8
	pop rbp
	pop r13
	pop r12
	pop rbx
	ret

;================================================================
; particle_burst_smoke
; in: edi = x_px, esi = y_px
;================================================================
particle_burst_smoke:
	push rbx
	push r12
	push r13
	push rbp
	sub rsp, 8

	mov r12d, edi
	mov r13d, esi

	mov ebp, 4
.s:
	mov edi, 3
	call rng_smallrange
	mov ebx, eax

	mov edi, 2
	call rng_smallrange
	sub eax, 3				; always-ish up

	mov edx, ebx
	shl edx, 12
	mov ecx, eax
	shl ecx, 14

	mov edi, r12d
	shl edi, 16
	mov esi, r13d
	shl esi, 16

	mov r8d, 0xC0B0B0B0
	mov r9d, 0x00404040

	push qword (P_FLAG_RECT | P_FLAG_WORLD_SPACE | P_FLAG_WIND)
	push qword 60
	call particle_spawn
	add rsp, 16

	dec ebp
	jnz .s

	add rsp, 8
	pop rbp
	pop r13
	pop r12
	pop rbx
	ret

%endif
